apiVersion: v1
kind: Namespace
metadata:
  name: retrymanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrymanager
  namespace: retrymanager
  labels:
    app: retrymanager
spec:
  selector:
    matchLabels:
      app: retrymanager
  template:
    metadata:
      labels:
        app: retrymanager
    spec:
      containers:
      - image: 566034038752.dkr.ecr.us-west-2.amazonaws.com/sykang/retrymanager:latest
        imagePullPolicy: Always
        name: retrymanager
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 250m
          requests:
            cpu: 100m
---          
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: retrymanager
  namespace: retrymanager
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: retrymanager
  minReplicas: 1
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # scale up if usage is above
          # 99% of the requested CPU (100m)
          averageUtilization: 50
